/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Intel i3-4010U
 */
public class PlayScreen extends javax.swing.JFrame {
    
    private Integer playerOne;
    private Integer playerTwo;
    /**
     * Creates new form menuScreen
     */
    public PlayScreen() {
        initComponents();
        //panelPlayer1.setBackground(new Color(0,0,0,0));
        playerTitle1.setVisible(true);
        playerTitle2.setVisible(false);
     //   exitButton.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        charizardButton = new javax.swing.JButton();
        pikachuButton = new javax.swing.JButton();
        snorlaxButton = new javax.swing.JButton();
        charmanderButton = new javax.swing.JButton();
        bulbasaurButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        playerTitle2 = new javax.swing.JLabel();
        playerTitle1 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 3));

        charizardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/charizardP.png"))); // NOI18N
        charizardButton.setText("Charizard");
        charizardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charizardButtonActionPerformed(evt);
            }
        });

        pikachuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/picachuP.png"))); // NOI18N
        pikachuButton.setText("Pikachu");
        pikachuButton.setBorderPainted(false);
        pikachuButton.setFocusPainted(false);
        pikachuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pikachuButtonActionPerformed(evt);
            }
        });

        snorlaxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/snorlaxP.png"))); // NOI18N
        snorlaxButton.setText("Snorlax");
        snorlaxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snorlaxButtonActionPerformed(evt);
            }
        });

        charmanderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/charmanderPP.png"))); // NOI18N
        charmanderButton.setText("Charmander");
        charmanderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charmanderButtonActionPerformed(evt);
            }
        });

        bulbasaurButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bulbasaurP.png"))); // NOI18N
        bulbasaurButton.setText("Bulbasaur");
        bulbasaurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulbasaurButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bulbasaurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charmanderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snorlaxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charizardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pikachuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(pikachuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(charizardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snorlaxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(charmanderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bulbasaurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(260, 100, 430, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vsC.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 250, 60, 50);

        playerTitle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/player2 P.png"))); // NOI18N
        jPanel1.add(playerTitle2);
        playerTitle2.setBounds(530, 30, 183, 54);

        playerTitle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/player1P.png"))); // NOI18N
        jPanel1.add(playerTitle1);
        playerTitle1.setBounds(260, 30, 183, 59);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu);
        menu.setBounds(43, 480, 60, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scene.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-40, -40, 1080, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pikachuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pikachuButtonActionPerformed
    
        if(playerTitle1.isVisible()== true){
            playerOne = 1;
            playerTitle1.setVisible(false);
            pikachuButton.setVisible(false);
            playerTitle2.setVisible(true);
        }else if(playerTitle1.isVisible() == false){
            playerTwo = 1;
            PlayersScreen screenPlayers = new PlayersScreen(playerOne, playerTwo);
            screenPlayers.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_pikachuButtonActionPerformed

    private void charizardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charizardButtonActionPerformed

        if(playerTitle1.isVisible() == true){
            playerOne = 2;
            playerTitle1.setVisible(false);
            charizardButton.setVisible(false);
            playerTitle2.setVisible(true);
        }else if(playerTitle1.isVisible() == false){
            playerTwo = 2;
            PlayersScreen screenPlayers = new PlayersScreen(playerOne, playerTwo);
            screenPlayers.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_charizardButtonActionPerformed

    private void snorlaxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snorlaxButtonActionPerformed
           
        if(playerTitle1.isVisible()== true){
            playerOne = 3;
            playerTitle1.setVisible(false);
            snorlaxButton.setVisible(false);
            playerTitle2.setVisible(true);
        }else if(playerTitle1.isVisible() == false){
            playerTwo = 3;
            PlayersScreen screenPlayers = new PlayersScreen(playerOne, playerTwo);
            screenPlayers.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_snorlaxButtonActionPerformed

    private void charmanderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charmanderButtonActionPerformed
          
        if(playerTitle1.isVisible()== true){
            playerOne = 4;
            playerTitle1.setVisible(false);
            charmanderButton.setVisible(false);
            playerTitle2.setVisible(true);
        }else if(playerTitle1.isVisible() == false){
            playerTwo = 4;
            PlayersScreen screenPlayers = new PlayersScreen(playerOne, playerTwo);
            screenPlayers.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_charmanderButtonActionPerformed

    private void bulbasaurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulbasaurButtonActionPerformed
        
        if(playerTitle1.isVisible()== true){
            playerOne = 5;
            playerTitle1.setVisible(false);
            bulbasaurButton.setVisible(false);
            playerTitle2.setVisible(true);
        }else if(playerTitle1.isVisible() == false){
            playerTwo = 5;
            PlayersScreen screenPlayers = new PlayersScreen(playerOne, playerTwo);
            screenPlayers.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_bulbasaurButtonActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        new MenuScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bulbasaurButton;
    private javax.swing.JButton charizardButton;
    private javax.swing.JButton charmanderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menu;
    private javax.swing.JButton pikachuButton;
    private javax.swing.JLabel playerTitle1;
    private javax.swing.JLabel playerTitle2;
    private javax.swing.JButton snorlaxButton;
    // End of variables declaration//GEN-END:variables
}
